version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server # user source code from the server directory
    volumes:
      - /app/node_modules # dont override the content of the mode module in the container (files are stored in the app folder)
      - ./server:/app # link everything in the server folder of our computer to the app folder of container keeping the link
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 # Default port the redis server listens to. Can be configured though
      - PGUSER=postgres
      - PGHOST=postgres # thats the name of the postgress service
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
